-- Supabase migration: Students table + ordered UCAGS0001 student ID generation
-- Date: 2026-02-20
--
-- This migration creates:
--  - public.students table
--  - a sequence for strictly-ordered numeric IDs
--  - a trigger to generate student_id like UCAGS0001
--  - optional enrollment tracking fields on public.registrations

-- Enable pgcrypto for gen_random_uuid()
create extension if not exists "pgcrypto";

-- 1) Enrollment fields on registrations (recommended)
alter table public.registrations
  add column if not exists enrolled boolean not null default false,
  add column if not exists enrolled_at timestamptz,
  add column if not exists student_id text;

create unique index if not exists registrations_student_id_unique
  on public.registrations (student_id)
  where student_id is not null;

create index if not exists registrations_enrolled_at_idx
  on public.registrations (enrolled_at);


-- 2) Students table
create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),

  -- UCAGS0001 style ID (generated by trigger below)
  student_id text unique,

  -- Link back to the source registration
  registration_id uuid unique,

  name text,
  phone_number text,
  email text,

  program_id uuid,
  program_name text,
  batch_name text,

  payload jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists students_program_id_idx on public.students (program_id);
create index if not exists students_batch_name_idx on public.students (batch_name);
create index if not exists students_created_at_idx on public.students (created_at);

-- Optional FK (only valid if registrations.id is uuid)
-- If your registrations.id is NOT uuid, comment this out and tell us.
alter table public.students
  drop constraint if exists students_registration_fk;

alter table public.students
  add constraint students_registration_fk
  foreign key (registration_id)
  references public.registrations (id)
  on delete set null;


-- 3) Strictly ordered student number sequence
create sequence if not exists public.student_number_seq
  as bigint
  start with 1662
  increment by 1
  minvalue 1;

-- 4) Trigger function to generate UCAGS0001 style IDs
create or replace function public.generate_ucags_student_id()
returns trigger
language plpgsql
as $$
declare
  n bigint;
begin
  -- Only generate if not provided
  if new.student_id is null or length(trim(new.student_id)) = 0 then
    n := nextval('public.student_number_seq');
    new.student_id := 'UCAGS/' || n::text;
  end if;
  return new;
end;
$$;

-- Trigger: before insert
drop trigger if exists trg_students_generate_id on public.students;
create trigger trg_students_generate_id
before insert on public.students
for each row
execute function public.generate_ucags_student_id();


-- 5) updated_at helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_students_updated_at on public.students;
create trigger trg_students_updated_at
before update on public.students
for each row
execute function public.set_updated_at();


-- 6) Backfill: if you already have students with student_id values, align the sequence
-- so the next generated ID continues from the current max.
-- This block is safe even if there are no rows.
do $$
declare
  max_n bigint;
begin
  select max((regexp_replace(student_id, '[^0-9]', '', 'g'))::bigint)
    into max_n
  from public.students
  where student_id is not null and student_id ~ '[0-9]';

  if max_n is not null then
    -- set sequence to max_n so nextval() returns max_n+1
    perform setval('public.student_number_seq', max_n);
  end if;
end;
$$;
